controller_joint_names: ['', 'Flexible_link_1', 'Arm_Link_1', 'Flexible_link_2', 'Arm_Link_2', 'Flexible_link_3', 'Arm_Link_3', 'Flexible_link_4', 'Arm_Link_4', 'Slider', 'Arm_1', 'Arm_2', 'Arm_3', 'Arm_4', ]
